### ISSUE TITLE
NextJS build in the 3.19.0 version

### ISSUE THREAD

**Issue by tsnery** [tabler/tabler-icons#1236]
### Description

Hello,

I am using NextJS 14.2.1 and tabler 3.19.0, and I'm trying to build my application after updates to this version of the tabler, but I'm getting an error.

Obs: My previous version of this package was 2.46.0, and this version is ok.

Here it is the error that I'm getting:

``` 
Creating an optimized production build ...

<--- Last few GCs --->

[17372:00000176473661A0]   141121 ms: Scavenge 3554.3 (4107.9) -> 3543.6 (4102.5) MB, 10.82 / 0.00 ms  (average mu = 0.237, current mu = 0.194) allocation failure;
[17372:00000176473661A0]   142661 ms: Mark-Compact 3565.1 (4119.0) -> 3554.0 (4097.5) MB, 1323.87 / 0.00 ms  (average mu = 0.228, current mu = 0.222) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF71A7E71AB node::SetCppgcReference+16075
 2: 00007FF71A75DCC6 v8::base::CPU::num_virtual_address_bits+79190
 3: 00007FF71A75FED5 v8::base::CPU::num_virtual_address_bits+87909
 4: 00007FF71B1CF061 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF71B1B87F8 v8::Function::Experimental_IsNopFunction+1336
 6: 00007FF71B01A120 v8::Platform::SystemClockTimeMillis+659328
 7: 00007FF71B0263A3 v8::Platform::SystemClockTimeMillis+709123
 8: 00007FF71B023D04 v8::Platform::SystemClockTimeMillis+699236
 9: 00007FF71B016E40 v8::Platform::SystemClockTimeMillis+646304
10: 00007FF71B02C4BA v8::Platform::SystemClockTimeMillis+733978
11: 00007FF71B02CD37 v8::Platform::SystemClockTimeMillis+736151
12: 00007FF71B03596E v8::Platform::SystemClockTimeMillis+772046
13: 00007FF71B04A1AA v8::Platform::SystemClockTimeMillis+856074
14: 00007FF71B04A493 v8::Platform::SystemClockTimeMillis+856819
15: 00007FF71ADD941D v8::base::Thread::StartSynchronously+465885
16: 00007FF71ADDA76D v8::base::Thread::StartSynchronously+470829
17: 00007FF71ADD9AD4 v8::base::Thread::StartSynchronously+467604
18: 00007FF71AD06B65 v8::CodeEvent::GetFunctionName+161701
19: 00007FF71B28062E v8::PropertyDescriptor::writable+677134
20: 00007FF71B2669F7 v8::PropertyDescriptor::writable+571607
21: 00007FF69BD3B785

> Build error occurred
Error: Jest worker encountered 1 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (D:\Documents\g1\portal\node_modules\next\dist\compiled\jest-worker\index.js:1:11580)
    at ChildProcessWorker._onExit (D:\Documents\g1\portal\node_modules\next\dist\compiled\jest-worker\index.js:1:12545)
    at ChildProcess.emit (node:events:530:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  type: 'WorkerError'
}```

### Package

- [ ] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [X] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.19.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

Build a Nextjs project with the @tabler/icons-react 3.19.0

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by public** [comment]
We worked around this by using the Babel `transform-imports` plugin in our Webpack config. A bit like this

```
    webpackConfig.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      exclude: /node_modules/,
      include: [/@tabler\/icons-react/],
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['next/babel'],
          plugins: [
            ['styled-components', { ssr: true, displayName: true }],
            [
              'transform-imports',
              {
                '@tabler/icons-react': {
                  transform: '@tabler/icons-react/dist/esm/icons/${member}',
                  preventFullImport: true,
                },
              },
            ],
          ],
        },
      },
    });
```
