### ISSUE TITLE
Can't `require()` svg icons after 2.0 update

### ISSUE THREAD

**Issue by alexgleason** [tabler/tabler-icons#496]
The change made here didn't seem to survive the 2.0 update: https://github.com/tabler/tabler-icons/pull/243

`require('@tabler/icons/calendar.svg')` results in:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@tabler/icons/calendar.svg' in '/builds/soapbox-pub/soapbox/app/soapbox/components'
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/Compilation.js:2016:28
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/builds/soapbox-pub/soapbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/builds/soapbox-pub/soapbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:[43](https://gitlab.com/soapbox-pub/soapbox/-/jobs/3677167835#L43)4:22
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /builds/soapbox-pub/soapbox/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@tabler/icons/calendar.svg' in '/builds/soapbox-pub/soapbox/app/soapbox/components'
  Parsed request is a module
  using description file: /builds/soapbox-pub/soapbox/package.json (relative path: ./app/soapbox/components)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /builds/soapbox-pub/soapbox/custom/modules
        /builds/soapbox-pub/soapbox/custom/modules/@tabler/icons doesn't exist
      looking for modules in /builds/soapbox-pub/soapbox/app
        /builds/soapbox-pub/soapbox/app/@tabler/icons doesn't exist
      /builds/soapbox-pub/soapbox/app/soapbox/components/node_modules doesn't exist or is not a directory
      /builds/soapbox-pub/soapbox/app/soapbox/node_modules doesn't exist or is not a directory
      /builds/soapbox-pub/soapbox/app/node_modules doesn't exist or is not a directory
      looking for modules in /builds/soapbox-pub/soapbox/node_modules
        existing directory /builds/soapbox-pub/soapbox/node_modules/@tabler/icons
          using description file: /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/package.json (relative path: .)
            using description file: /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/package.json (relative path: ./calendar.svg)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.jsx doesn't exist
              .cjs
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.cjs doesn't exist
              .mjs
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.mjs doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.tsx doesn't exist
              .sass
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.sass doesn't exist
              .scss
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.scss doesn't exist
              .css
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.css doesn't exist
              .module.sass
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.module.sass doesn't exist
              .module.scss
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.module.scss doesn't exist
              .module.css
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.module.css doesn't exist
              .png
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.png doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.svg doesn't exist
              .gif
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.gif doesn't exist
              .jpeg
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.jpeg doesn't exist
              .jpg
                Field 'browser' doesn't contain a valid alias configuration
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg.jpg doesn't exist
              as directory
                /builds/soapbox-pub/soapbox/node_modules/@tabler/icons/calendar.svg doesn't exist
      /builds/soapbox-pub/node_modules doesn't exist or is not a directory
      /builds/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

https://gitlab.com/soapbox-pub/soapbox/-/merge_requests/2218

**Comment by gi8ri7** [comment]
J

**Comment by mazipan** [comment]
Have you try to use `@tabler/icons-react`?

**Comment by codecalm** [comment]
it should be fixed now :)
